# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Captionizer.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 720)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 720))
        MainWindow.setAcceptDrops(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/logo/resources/logo/Captionizer_Logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(1000, 720))
        self.centralwidget.setStyleSheet("/* Main */\n"
"#frm_main{\n"
"    background-color: #272c36;\n"
"    border: none;\n"
"}\n"
"#window_top, #window_bottom, #window_left, #window_right, \n"
"#window_topLeft, #window_topRight, #window_bottomLeft, #window_bottomRight{\n"
"    background-color: #3c3c3c;\n"
"}\n"
"*{\n"
"    color: #eeeeee;\n"
"}\n"
"QToolTip {\n"
"    color: #ffffff;\n"
"    background-color: #2d2b2b;\n"
"    border: 1px solid #2d2b2b;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frm_window = QtWidgets.QFrame(self.centralwidget)
        self.frm_window.setAutoFillBackground(False)
        self.frm_window.setStyleSheet("#frm_window { border-radius: 20px; }")
        self.frm_window.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_window.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_window.setObjectName("frm_window")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frm_window)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.window_topRight = QtWidgets.QFrame(self.frm_window)
        self.window_topRight.setMinimumSize(QtCore.QSize(0, 0))
        self.window_topRight.setMaximumSize(QtCore.QSize(2, 2))
        self.window_topRight.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.window_topRight.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.window_topRight.setFrameShadow(QtWidgets.QFrame.Raised)
        self.window_topRight.setObjectName("window_topRight")
        self.gridLayout_3.addWidget(self.window_topRight, 0, 2, 1, 1)
        self.window_topLeft = QtWidgets.QFrame(self.frm_window)
        self.window_topLeft.setMinimumSize(QtCore.QSize(0, 0))
        self.window_topLeft.setMaximumSize(QtCore.QSize(2, 2))
        self.window_topLeft.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.window_topLeft.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.window_topLeft.setFrameShadow(QtWidgets.QFrame.Raised)
        self.window_topLeft.setObjectName("window_topLeft")
        self.gridLayout_3.addWidget(self.window_topLeft, 0, 0, 1, 1)
        self.window_left = QtWidgets.QFrame(self.frm_window)
        self.window_left.setMinimumSize(QtCore.QSize(0, 0))
        self.window_left.setMaximumSize(QtCore.QSize(2, 16777215))
        self.window_left.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.window_left.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.window_left.setFrameShadow(QtWidgets.QFrame.Raised)
        self.window_left.setObjectName("window_left")
        self.gridLayout_3.addWidget(self.window_left, 2, 0, 1, 1)
        self.window_right = QtWidgets.QFrame(self.frm_window)
        self.window_right.setMinimumSize(QtCore.QSize(0, 0))
        self.window_right.setMaximumSize(QtCore.QSize(2, 16777215))
        self.window_right.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.window_right.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.window_right.setFrameShadow(QtWidgets.QFrame.Raised)
        self.window_right.setObjectName("window_right")
        self.gridLayout_3.addWidget(self.window_right, 2, 2, 1, 1)
        self.frm_main = QtWidgets.QFrame(self.frm_window)
        self.frm_main.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_main.setObjectName("frm_main")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.frm_main)
        self.verticalLayout_27.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_27.setSpacing(0)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.frm_titlebar = QtWidgets.QFrame(self.frm_main)
        self.frm_titlebar.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frm_titlebar.setStyleSheet("/* Title Bar */\n"
"#frm_titlebar, #frm_windowControl, #frm_windowTitlebar{\n"
"    border: none;\n"
"    height: 30px;\n"
"    background-color: #3c3c3c;\n"
"}\n"
"#frm_windowControl{\n"
"    width: 135px;\n"
"}")
        self.frm_titlebar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_titlebar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_titlebar.setObjectName("frm_titlebar")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frm_titlebar)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frm_windowTitlebar = QtWidgets.QFrame(self.frm_titlebar)
        self.frm_windowTitlebar.setMinimumSize(QtCore.QSize(0, 30))
        self.frm_windowTitlebar.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frm_windowTitlebar.setStyleSheet("/* Window Title Bar */\n"
"#lbl_windowLogo{\n"
"    width: 30px;\n"
"}\n"
"#lbl_windowTitle{\n"
"    font: 16pt \"Lobster\";\n"
"}\n"
"#frm_windowTitle > QPushButton{\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    font-family: Verdana;\n"
"    text-align: center;\n"
"}\n"
"#frm_windowTitle > QPushButton:hover{\n"
"    background-color: #6f6f6f;\n"
"}\n"
"#frm_windowTitle > QPushButton:pressed{\n"
"    background-color: #282525;\n"
"}\n"
"#frm_windowTitle > QPushButton::menu-indicator{ \n"
"    image: none;\n"
"    width: 0px;\n"
"}")
        self.frm_windowTitlebar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_windowTitlebar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_windowTitlebar.setObjectName("frm_windowTitlebar")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frm_windowTitlebar)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frm_windowLogo = QtWidgets.QFrame(self.frm_windowTitlebar)
        self.frm_windowLogo.setMinimumSize(QtCore.QSize(30, 30))
        self.frm_windowLogo.setMaximumSize(QtCore.QSize(30, 30))
        self.frm_windowLogo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_windowLogo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_windowLogo.setObjectName("frm_windowLogo")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frm_windowLogo)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 3)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lbl_windowLogo = QtWidgets.QLabel(self.frm_windowLogo)
        self.lbl_windowLogo.setMinimumSize(QtCore.QSize(24, 24))
        self.lbl_windowLogo.setMaximumSize(QtCore.QSize(24, 24))
        self.lbl_windowLogo.setText("")
        self.lbl_windowLogo.setPixmap(QtGui.QPixmap(":/logo/resources/logo/Captionizer_Logo.png"))
        self.lbl_windowLogo.setScaledContents(True)
        self.lbl_windowLogo.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_windowLogo.setObjectName("lbl_windowLogo")
        self.horizontalLayout_6.addWidget(self.lbl_windowLogo)
        self.horizontalLayout_3.addWidget(self.frm_windowLogo)
        self.frm_windowTitle = QtWidgets.QFrame(self.frm_windowTitlebar)
        self.frm_windowTitle.setStyleSheet("")
        self.frm_windowTitle.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_windowTitle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_windowTitle.setObjectName("frm_windowTitle")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frm_windowTitle)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lbl_windowTitle = QtWidgets.QLabel(self.frm_windowTitle)
        self.lbl_windowTitle.setMinimumSize(QtCore.QSize(110, 0))
        self.lbl_windowTitle.setMaximumSize(QtCore.QSize(110, 30))
        font = QtGui.QFont()
        font.setFamily("Lobster")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lbl_windowTitle.setFont(font)
        self.lbl_windowTitle.setObjectName("lbl_windowTitle")
        self.horizontalLayout_5.addWidget(self.lbl_windowTitle)
        self.mnu_file = QtWidgets.QPushButton(self.frm_windowTitle)
        self.mnu_file.setMinimumSize(QtCore.QSize(30, 30))
        self.mnu_file.setMaximumSize(QtCore.QSize(30, 30))
        self.mnu_file.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.mnu_file.setObjectName("mnu_file")
        self.horizontalLayout_5.addWidget(self.mnu_file)
        self.mnu_history = QtWidgets.QPushButton(self.frm_windowTitle)
        self.mnu_history.setMinimumSize(QtCore.QSize(50, 30))
        self.mnu_history.setMaximumSize(QtCore.QSize(50, 30))
        self.mnu_history.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.mnu_history.setObjectName("mnu_history")
        self.horizontalLayout_5.addWidget(self.mnu_history)
        self.horizontalLayout_3.addWidget(self.frm_windowTitle, 0, QtCore.Qt.AlignLeft)
        self.horizontalLayout_2.addWidget(self.frm_windowTitlebar)
        self.frm_windowControl = QtWidgets.QFrame(self.frm_titlebar)
        self.frm_windowControl.setMinimumSize(QtCore.QSize(135, 30))
        self.frm_windowControl.setMaximumSize(QtCore.QSize(135, 30))
        self.frm_windowControl.setStyleSheet("/* Window Controls */\n"
"#frm_windowControl > QPushButton{\n"
"    border: none;\n"
"    background-color: transparent;\n"
"}\n"
"#frm_windowControl > QPushButton:hover{\n"
"    background-color: #505050;\n"
"}\n"
"#frm_windowControl > QPushButton:pressed{\n"
"    background-color: #000000;\n"
"}")
        self.frm_windowControl.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_windowControl.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_windowControl.setObjectName("frm_windowControl")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frm_windowControl)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btn_minimize = QtWidgets.QPushButton(self.frm_windowControl)
        self.btn_minimize.setMinimumSize(QtCore.QSize(45, 30))
        self.btn_minimize.setMaximumSize(QtCore.QSize(45, 30))
        self.btn_minimize.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_minimize.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/windows_control/resources/window_controls/minimize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_minimize.setIcon(icon1)
        self.btn_minimize.setIconSize(QtCore.QSize(16, 16))
        self.btn_minimize.setObjectName("btn_minimize")
        self.horizontalLayout_4.addWidget(self.btn_minimize)
        self.btn_maximize = QtWidgets.QPushButton(self.frm_windowControl)
        self.btn_maximize.setMinimumSize(QtCore.QSize(45, 30))
        self.btn_maximize.setMaximumSize(QtCore.QSize(45, 30))
        self.btn_maximize.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_maximize.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/windows_control/resources/window_controls/maximize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_maximize.setIcon(icon2)
        self.btn_maximize.setIconSize(QtCore.QSize(16, 16))
        self.btn_maximize.setObjectName("btn_maximize")
        self.horizontalLayout_4.addWidget(self.btn_maximize)
        self.btn_close = QtWidgets.QPushButton(self.frm_windowControl)
        self.btn_close.setMinimumSize(QtCore.QSize(45, 30))
        self.btn_close.setMaximumSize(QtCore.QSize(45, 30))
        self.btn_close.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_close.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/windows_control/resources/window_controls/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_close.setIcon(icon3)
        self.btn_close.setIconSize(QtCore.QSize(16, 16))
        self.btn_close.setFlat(False)
        self.btn_close.setObjectName("btn_close")
        self.horizontalLayout_4.addWidget(self.btn_close)
        self.horizontalLayout_2.addWidget(self.frm_windowControl)
        self.verticalLayout_27.addWidget(self.frm_titlebar)
        self.frm_display = QtWidgets.QFrame(self.frm_main)
        self.frm_display.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_display.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_display.setObjectName("frm_display")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frm_display)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frm_menubar = QtWidgets.QFrame(self.frm_display)
        self.frm_menubar.setMinimumSize(QtCore.QSize(70, 0))
        self.frm_menubar.setMaximumSize(QtCore.QSize(70, 16777215))
        self.frm_menubar.setStyleSheet("/* Menubar */\n"
"#frm_menubar, #frm_menus{\n"
"    background-color: #1b1d23;\n"
"    border: none;\n"
"}\n"
"#frm_menus > QPushButton{\n"
"    background-position: left center;\n"
"    background-repeat: no-repeat;\n"
"    border: none;\n"
"    border-left: 19px solid transparent;\n"
"    height: 70px;\n"
"    width: 140px;\n"
"    padding-left: 55px;\n"
"    text-align: left;\n"
"    font: bold 12pt \"Secular One\";\n"
"}\n"
"#frm_menus > QPushButton:hover{\n"
"    background-color: #45464a;\n"
"    border-left: 19px solid #45464a;\n"
"    border-right: 5px solid #45464a;\n"
"}\n"
"#frm_menus > QPushButton:pressed{\n"
"    background-color: #030406;\n"
"    border-left: 19px solid #030406;\n"
"    border-right: 5px solid #030406;\n"
"}\n"
"#frm_menus #btn_menu{\n"
"    background-image: url(:/menu/resources/menu/hamburger.png);\n"
"    border-bottom: 2px solid #666666;\n"
"}\n"
"#frm_menus #btn_menuTranscription{\n"
"    background-image: url(:/menu/resources/menu/transcribe.png);\n"
"}\n"
"#frm_menus #btn_menuTranslation{\n"
"    background-image: url(:/menu/resources/menu/translate.png);\n"
"}")
        self.frm_menubar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_menubar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_menubar.setObjectName("frm_menubar")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frm_menubar)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frm_menus = QtWidgets.QFrame(self.frm_menubar)
        self.frm_menus.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_menus.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_menus.setObjectName("frm_menus")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frm_menus)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.btn_menu = QtWidgets.QPushButton(self.frm_menus)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_menu.sizePolicy().hasHeightForWidth())
        self.btn_menu.setSizePolicy(sizePolicy)
        self.btn_menu.setMinimumSize(QtCore.QSize(70, 0))
        self.btn_menu.setMaximumSize(QtCore.QSize(300, 16777215))
        self.btn_menu.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_menu.setIconSize(QtCore.QSize(70, 70))
        self.btn_menu.setObjectName("btn_menu")
        self.verticalLayout_4.addWidget(self.btn_menu)
        self.btn_menuTranscription = QtWidgets.QPushButton(self.frm_menus)
        self.btn_menuTranscription.setMaximumSize(QtCore.QSize(300, 70))
        self.btn_menuTranscription.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_menuTranscription.setObjectName("btn_menuTranscription")
        self.verticalLayout_4.addWidget(self.btn_menuTranscription)
        self.btn_menuTranslation = QtWidgets.QPushButton(self.frm_menus)
        self.btn_menuTranslation.setMaximumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setFamily("Secular One")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btn_menuTranslation.setFont(font)
        self.btn_menuTranslation.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_menuTranslation.setObjectName("btn_menuTranslation")
        self.verticalLayout_4.addWidget(self.btn_menuTranslation)
        self.verticalLayout_3.addWidget(self.frm_menus, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout.addWidget(self.frm_menubar)
        self.frm_content = QtWidgets.QFrame(self.frm_display)
        self.frm_content.setStyleSheet("/* Content */\n"
"#frm_content, #stackedWidget, #stackedWidget > QWidget{\n"
"    background-color: #2c313c;\n"
"}")
        self.frm_content.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_content.setObjectName("frm_content")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frm_content)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frm_content)
        self.stackedWidget.setStyleSheet("/* Common Style */\n"
"QPushButton{\n"
"    border-radius: 5px;\n"
"    background-color: #343b48;\n"
"}\n"
"QPushButton:hover{\n"
"    border: 1px solid #3d4656;\n"
"    background-color: #394150;\n"
"}\n"
"QPushButton:pressed{\n"
"    border: 1px solid #2b323d;\n"
"    background-color: #232831;\n"
"}\n"
"QPushButton:disabled{\n"
"    color: #cccccc;\n"
"    background-color: #585d68;\n"
"}\n"
"QProgressBar{\n"
"    color: #000;\n"
"    text-align: center;\n"
"    font-family: Arial, Helvetica, sans-serif;\n"
"}\n"
"QListWidget{\n"
"    border: 2px solid #627094;\n"
"    border-radius: 15px;\n"
"    background-color: #0e1118;\n"
"}\n"
"QListWidget:item{\n"
"    height: 25px;\n"
"    font-size: 10pt;\n"
"}\n"
"QAbstractScrollArea:corner{\n"
"    border-bottom-right-radius: 11px;\n"
"}\n"
"QScrollBar:handle{\n"
"    background-color: #1884ce;\n"
"}\n"
"QScrollBar:handle:hover{\n"
"    background-color: #4ca0d8;\n"
"}\n"
"QScrollBar:handle:pressed{\n"
"    background-color: #1a567e;\n"
"}\n"
"QScrollBar:vertical{\n"
"    background-color: #343b48;\n"
"    border-radius: 7px;\n"
"    width: 19px;\n"
"    margin-top: 5px;\n"
"    margin-right: 5px;\n"
"}\n"
"QScrollBar:handle:vertical{\n"
"    border-radius: 7px;\n"
"}\n"
"QScrollBar:add-line:vertical{\n"
"    border-bottom-left-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"}\n"
"QScrollBar:sub-line:vertical{\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"}\n"
"QScrollBar:add-page:vertical{\n"
"    background-color: #343b48;\n"
"    border-bottom-left-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"}\n"
"QScrollBar:sub-page:vertical{\n"
"    background-color: #343b48;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"}\n"
"QScrollBar:horizontal{\n"
"    background-color: #343b48;\n"
"    border-radius: 7px;\n"
"    height: 19px;\n"
"    margin-left: 5px;\n"
"    margin-bottom: 5px;\n"
"}\n"
"QScrollBar:handle:horizontal{\n"
"    border-radius: 7px;\n"
"}\n"
"QScrollBar:add-line:horizontal{\n"
"    border-top-right-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"}\n"
"QScrollBar:sub-line:horizontal{\n"
"    border-top-left-radius: 7px;\n"
"    border-bottom-left-radius: 7px;\n"
"}\n"
"QScrollBar:add-page:horizontal{\n"
"    background-color: #343b48;\n"
"    border-top-right-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"}\n"
"QScrollBar:sub-page:horizontal{\n"
"    background-color: #343b48;\n"
"    border-top-left-radius: 7px;\n"
"    border-bottom-left-radius: 7px;\n"
"}\n"
"QComboBox{\n"
"    background-color: transparent;\n"
"    border: 1px solid #7a7a7a;\n"
"    border-radius: 3px;\n"
"    font: 10pt \'Franklin Gothic Medium\';\n"
"    padding-left: 5px;\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #272c36;\n"
"    min-width: 200px;\n"
"}\n"
"QComboBox:hover{\n"
"    background-color: #565960;\n"
"}\n"
"QComboBox::down-arrow{\n"
"    image: url(:/icons/resources/icons/down_arrow.png);\n"
"}\n"
"QComboBox:disabled{\n"
"    color: #cccccc;\n"
"    background-color: #404c63;\n"
"}\n"
"QLineEdit{\n"
"    border: 1px solid #7a7a7a;\n"
"    border-right: none;\n"
"    border-top-left-radius: 3px;\n"
"    border-bottom-left-radius: 3px;\n"
"    font: 10pt \'Franklin Gothic Medium\';\n"
"    color: #101010;\n"
"    padding-left: 5px;\n"
"}\n"
"QLineEdit:hover:!focus{\n"
"    background-color: #565960;\n"
"}\n"
"QCheckBox{\n"
"    padding-left: 5px;\n"
"    font: 10pt \'Franklin Gothic Medium\';\n"
"}\n"
"QCheckBox:disabled{\n"
"    color: #888888\n"
"}")
        self.stackedWidget.setObjectName("stackedWidget")
        self.pg_mainMenu = QtWidgets.QWidget()
        self.pg_mainMenu.setStyleSheet("/* Main Menu */\n"
"#frm_mainMenu{\n"
"    border: 5px outset #272c36;\n"
"    border-radius: 25px;\n"
"    background-color: #2f3644;\n"
"}\n"
"#frm_mainMenu_title{\n"
"    border: none;\n"
"    border-bottom: 1px groove #888888;\n"
"}\n"
"#lbl_mainMenu_title{\n"
"    font: 30pt \'Lobster\';\n"
"}\n"
"#frm_mainMenu_tabs > QPushButton{\n"
"    font: bold 12pt \'Secular One\';\n"
"    text-align: left;\n"
"    padding-left: 25px;\n"
"    border: 2px solid #404a5c;\n"
"    border-radius: 15px;\n"
"    background-color: #1b1d23;\n"
"}\n"
"#frm_mainMenu_tabs > QPushButton:hover{\n"
"    background-color: #394150;\n"
"}\n"
"#frm_mainMenu_tabs > QPushButton:pressed{\n"
"    border: 2px solid #2b323d;\n"
"    background-color: #232831;\n"
"}")
        self.pg_mainMenu.setObjectName("pg_mainMenu")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.pg_mainMenu)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.frm_mainMenu = QtWidgets.QFrame(self.pg_mainMenu)
        self.frm_mainMenu.setMinimumSize(QtCore.QSize(500, 500))
        self.frm_mainMenu.setMaximumSize(QtCore.QSize(500, 500))
        self.frm_mainMenu.setStyleSheet("")
        self.frm_mainMenu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_mainMenu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_mainMenu.setObjectName("frm_mainMenu")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.frm_mainMenu)
        self.verticalLayout_24.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_24.setSpacing(10)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.frm_mainMenu_title = QtWidgets.QFrame(self.frm_mainMenu)
        self.frm_mainMenu_title.setMinimumSize(QtCore.QSize(0, 60))
        self.frm_mainMenu_title.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frm_mainMenu_title.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_mainMenu_title.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_mainMenu_title.setObjectName("frm_mainMenu_title")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.frm_mainMenu_title)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.lbl_mainMenu_title = QtWidgets.QLabel(self.frm_mainMenu_title)
        self.lbl_mainMenu_title.setMinimumSize(QtCore.QSize(0, 0))
        self.lbl_mainMenu_title.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_mainMenu_title.setObjectName("lbl_mainMenu_title")
        self.verticalLayout_25.addWidget(self.lbl_mainMenu_title)
        self.verticalLayout_24.addWidget(self.frm_mainMenu_title)
        self.frm_mainMenu_tabs = QtWidgets.QFrame(self.frm_mainMenu)
        self.frm_mainMenu_tabs.setMinimumSize(QtCore.QSize(300, 0))
        self.frm_mainMenu_tabs.setMaximumSize(QtCore.QSize(300, 16777215))
        self.frm_mainMenu_tabs.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_mainMenu_tabs.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_mainMenu_tabs.setObjectName("frm_mainMenu_tabs")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.frm_mainMenu_tabs)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.btn_mainMenu_transcription = QtWidgets.QPushButton(self.frm_mainMenu_tabs)
        self.btn_mainMenu_transcription.setMaximumSize(QtCore.QSize(300, 70))
        self.btn_mainMenu_transcription.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/menu/resources/menu/transcribe.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_mainMenu_transcription.setIcon(icon4)
        self.btn_mainMenu_transcription.setIconSize(QtCore.QSize(32, 32))
        self.btn_mainMenu_transcription.setObjectName("btn_mainMenu_transcription")
        self.verticalLayout_26.addWidget(self.btn_mainMenu_transcription)
        self.btn_mainMenu_translation = QtWidgets.QPushButton(self.frm_mainMenu_tabs)
        self.btn_mainMenu_translation.setMaximumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setFamily("Secular One")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btn_mainMenu_translation.setFont(font)
        self.btn_mainMenu_translation.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/menu/resources/menu/translate.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_mainMenu_translation.setIcon(icon5)
        self.btn_mainMenu_translation.setIconSize(QtCore.QSize(32, 32))
        self.btn_mainMenu_translation.setObjectName("btn_mainMenu_translation")
        self.verticalLayout_26.addWidget(self.btn_mainMenu_translation)
        self.verticalLayout_24.addWidget(self.frm_mainMenu_tabs, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_23.addWidget(self.frm_mainMenu, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.stackedWidget.addWidget(self.pg_mainMenu)
        self.pg_transcribe = QtWidgets.QWidget()
        self.pg_transcribe.setStyleSheet("/* Transcribe */\n"
"#frm_transcribe_top > QFrame{\n"
"    border: 1px solid transparent;\n"
"    border-radius: 15px;\n"
"    background-color: #272c36;\n"
"}\n"
"#frm_transcribe_bottom{\n"
"    border: 1px solid transparent;\n"
"    border-radius: 15px;\n"
"    background-color: #272c36;\n"
"    margin: 9px;\n"
"}\n"
"#frm_transcribe_separator{\n"
"    border-radius: 0px;\n"
"    background-color: #3d4656;\n"
"}\n"
"\n"
"/* Transcribe File Frame */\n"
"#lbl_transcribe_title{\n"
"    font: bold 14pt \'Segoe UI\';\n"
"    color: #cccccc;\n"
"    padding-left: 1px;\n"
"}\n"
"#frm_transcribe_file_buttons{\n"
"    height: 30px;\n"
"}\n"
"#lbl_transcribe_file_import, #lbl_transcribe_status{\n"
"    font: italic Arial, Helvetica, sans-serif;\n"
"}\n"
"\n"
"/* Transcribe Audio Player */\n"
"#lbl_transcribe_player_status{\n"
"    font: italic bold Arial, Helvetica, sans-serif;\n"
"    text-align: center;\n"
"    color: #ff3333;\n"
"}\n"
"#frm_transcribe_player_slider QLabel{\n"
"    font-family: Palatino;\n"
"}\n"
"#sld_transcribe_player::groove{\n"
"    border-radius: 1px;\n"
"    background: #484f5a;\n"
"    height: 2px;\n"
"}\n"
"#sld_transcribe_player::handle{\n"
"    background-color: #007ad9;\n"
"    height: 14px;\n"
"    width: 14px;\n"
"    margin: -7px 0;\n"
"    border-radius: 7px;\n"
"}\n"
"#sld_transcribe_player::handle:disabled{\n"
"    background-color: #416988;\n"
"}\n"
"#sld_transcribe_player::groove:hover{\n"
"    background-color: #787878;\n"
"}\n"
"#sld_transcribe_player::handle:hover{\n"
"    background-color: #005cbb;\n"
"}\n"
"#sld_transcribe_player::sub-page {\n"
"    background: #3288df;\n"
"}\n"
"#frm_transcribe_player_buttons #btn_transcribe_player_play, \n"
"#frm_transcribe_player_buttons #btn_transcribe_player_pause, \n"
"#frm_transcribe_player_buttons #btn_transcribe_player_stop{\n"
"    margin: 1px;\n"
"    background-color: transparent;\n"
"}\n"
"#btn_transcribe_player_play:disabled, #btn_transcribe_player_pause:disabled, #btn_transcribe_player_stop:disabled{\n"
"    border-radius: 0px;\n"
"    background-color: #404c63;\n"
"}\n"
"\n"
"/* Transcribe Input */\n"
"#frm_transcribe_input QLabel{\n"
"    font: 10pt \'Franklin Gothic Medium\';\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;\n"
"}\n"
"#btn_transcribe_output{\n"
"    border: 1px solid #7a7a7a;\n"
"    border-radius: 0px;\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"\n"
"/* Transcribe Form Transcribe */\n"
"#pgr_transcribe_transcribe{\n"
"    margin-bottom: -20px;\n"
"}\n"
"#lbl_transcribe_status{\n"
"    font: italic Arial, Helvetica, sans-serif;\n"
"    margin-top: -20px;\n"
"}\n"
"#frm_transcribe_transcribe > QPushButton{\n"
"    border: 4px ridge #333d50;\n"
"    border-radius: 15px;\n"
"}\n"
"#frm_transcribe_transcribe > QPushButton:hover{\n"
"    border: 4px ridge #3e4c66;\n"
"}\n"
"#frm_transcribe_transcribe > QPushButton:pressed{\n"
"    border: 4px solid #15171a;\n"
"}\n"
"#btn_transcribe_transcribe{\n"
"    font: bold 12pt \"Secular One\";\n"
"}\n"
"#btn_transcribe_cancel{\n"
"    font: \'Segoe UI\';\n"
"}")
        self.pg_transcribe.setObjectName("pg_transcribe")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.pg_transcribe)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frm_transcribe = QtWidgets.QFrame(self.pg_transcribe)
        self.frm_transcribe.setStyleSheet("")
        self.frm_transcribe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_transcribe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_transcribe.setObjectName("frm_transcribe")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frm_transcribe)
        self.verticalLayout_8.setContentsMargins(-1, -1, -1, 9)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frm_transcribe_top = QtWidgets.QFrame(self.frm_transcribe)
        self.frm_transcribe_top.setEnabled(True)
        self.frm_transcribe_top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_transcribe_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_transcribe_top.setObjectName("frm_transcribe_top")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frm_transcribe_top)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frm_transcribe_file = QtWidgets.QFrame(self.frm_transcribe_top)
        self.frm_transcribe_file.setStyleSheet("")
        self.frm_transcribe_file.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_transcribe_file.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_transcribe_file.setObjectName("frm_transcribe_file")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frm_transcribe_file)
        self.verticalLayout_10.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_10.setSpacing(8)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.lbl_transcribe_title = QtWidgets.QLabel(self.frm_transcribe_file)
        self.lbl_transcribe_title.setMinimumSize(QtCore.QSize(0, 24))
        self.lbl_transcribe_title.setMaximumSize(QtCore.QSize(16777215, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.lbl_transcribe_title.setFont(font)
        self.lbl_transcribe_title.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_transcribe_title.setObjectName("lbl_transcribe_title")
        self.verticalLayout_10.addWidget(self.lbl_transcribe_title)
        self.frm_transcribe_file_buttons = QtWidgets.QFrame(self.frm_transcribe_file)
        self.frm_transcribe_file_buttons.setMaximumSize(QtCore.QSize(100, 30))
        self.frm_transcribe_file_buttons.setStyleSheet("")
        self.frm_transcribe_file_buttons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_transcribe_file_buttons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_transcribe_file_buttons.setObjectName("frm_transcribe_file_buttons")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frm_transcribe_file_buttons)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(5)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.btn_transcribe_file_add = QtWidgets.QPushButton(self.frm_transcribe_file_buttons)
        self.btn_transcribe_file_add.setEnabled(True)
        self.btn_transcribe_file_add.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_transcribe_file_add.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_transcribe_file_add.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_transcribe_file_add.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/resources/icons/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon6.addPixmap(QtGui.QPixmap(":/icons/resources/icons/add_disabled.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        self.btn_transcribe_file_add.setIcon(icon6)
        self.btn_transcribe_file_add.setObjectName("btn_transcribe_file_add")
        self.horizontalLayout_7.addWidget(self.btn_transcribe_file_add)
        self.btn_transcribe_file_remove = QtWidgets.QPushButton(self.frm_transcribe_file_buttons)
        self.btn_transcribe_file_remove.setEnabled(True)
        self.btn_transcribe_file_remove.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_transcribe_file_remove.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_transcribe_file_remove.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_transcribe_file_remove.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/resources/icons/minus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon7.addPixmap(QtGui.QPixmap(":/icons/resources/icons/minus_disabled.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        self.btn_transcribe_file_remove.setIcon(icon7)
        self.btn_transcribe_file_remove.setObjectName("btn_transcribe_file_remove")
        self.horizontalLayout_7.addWidget(self.btn_transcribe_file_remove)
        self.btn_transcribe_file_record = QtWidgets.QPushButton(self.frm_transcribe_file_buttons)
        self.btn_transcribe_file_record.setEnabled(True)
        self.btn_transcribe_file_record.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_transcribe_file_record.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_transcribe_file_record.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_transcribe_file_record.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/resources/icons/microphone.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon8.addPixmap(QtGui.QPixmap(":/icons/resources/icons/microphone_disabled.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        self.btn_transcribe_file_record.setIcon(icon8)
        self.btn_transcribe_file_record.setIconSize(QtCore.QSize(20, 20))
        self.btn_transcribe_file_record.setObjectName("btn_transcribe_file_record")
        self.horizontalLayout_7.addWidget(self.btn_transcribe_file_record)
        self.verticalLayout_10.addWidget(self.frm_transcribe_file_buttons)
        self.frm_transcribe_file_list = QtWidgets.QFrame(self.frm_transcribe_file)
        self.frm_transcribe_file_list.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_transcribe_file_list.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_transcribe_file_list.setObjectName("frm_transcribe_file_list")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frm_transcribe_file_list)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.lst_transcribe_file = QtWidgets.QListWidget(self.frm_transcribe_file_list)
        self.lst_transcribe_file.setStyleSheet("")
        self.lst_transcribe_file.setAlternatingRowColors(False)
        self.lst_transcribe_file.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.lst_transcribe_file.setObjectName("lst_transcribe_file")
        self.verticalLayout_12.addWidget(self.lst_transcribe_file)
        self.verticalLayout_10.addWidget(self.frm_transcribe_file_list)
        self.frm_transcribe_file_progress = QtWidgets.QFrame(self.frm_transcribe_file)
        self.frm_transcribe_file_progress.setMinimumSize(QtCore.QSize(0, 0))
        self.frm_transcribe_file_progress.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frm_transcribe_file_progress.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_transcribe_file_progress.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_transcribe_file_progress.setObjectName("frm_transcribe_file_progress")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frm_transcribe_file_progress)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.pgr_transcribe_file_import = QtWidgets.QProgressBar(self.frm_transcribe_file_progress)
        self.pgr_transcribe_file_import.setMinimumSize(QtCore.QSize(0, 21))
        self.pgr_transcribe_file_import.setMaximumSize(QtCore.QSize(16777215, 21))
        self.pgr_transcribe_file_import.setProperty("value", 0)
        self.pgr_transcribe_file_import.setObjectName("pgr_transcribe_file_import")
        self.verticalLayout_11.addWidget(self.pgr_transcribe_file_import)
        self.lbl_transcribe_file_import = QtWidgets.QLabel(self.frm_transcribe_file_progress)
        self.lbl_transcribe_file_import.setMinimumSize(QtCore.QSize(0, 21))
        self.lbl_transcribe_file_import.setMaximumSize(QtCore.QSize(16777215, 21))
        self.lbl_transcribe_file_import.setText("")
        self.lbl_transcribe_file_import.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_transcribe_file_import.setObjectName("lbl_transcribe_file_import")
        self.verticalLayout_11.addWidget(self.lbl_transcribe_file_import)
        self.verticalLayout_10.addWidget(self.frm_transcribe_file_progress)
        self.verticalLayout_9.addWidget(self.frm_transcribe_file)
        self.frm_transcribe_player = QtWidgets.QFrame(self.frm_transcribe_top)
        self.frm_transcribe_player.setEnabled(True)
        self.frm_transcribe_player.setMaximumSize(QtCore.QSize(16777215, 65))
        self.frm_transcribe_player.setStyleSheet("")
        self.frm_transcribe_player.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_transcribe_player.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_transcribe_player.setObjectName("frm_transcribe_player")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frm_transcribe_player)
        self.horizontalLayout_8.setContentsMargins(5, 5, 5, 0)
        self.horizontalLayout_8.setSpacing(5)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.frm_transcribe_player_buttons = QtWidgets.QFrame(self.frm_transcribe_player)
        self.frm_transcribe_player_buttons.setEnabled(True)
        self.frm_transcribe_player_buttons.setMinimumSize(QtCore.QSize(0, 0))
        self.frm_transcribe_player_buttons.setMaximumSize(QtCore.QSize(90, 65))
        self.frm_transcribe_player_buttons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_transcribe_player_buttons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_transcribe_player_buttons.setObjectName("frm_transcribe_player_buttons")
        self.gridLayout = QtWidgets.QGridLayout(self.frm_transcribe_player_buttons)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setVerticalSpacing(3)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_transcribe_player_pause = QtWidgets.QPushButton(self.frm_transcribe_player_buttons)
        self.btn_transcribe_player_pause.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_transcribe_player_pause.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_transcribe_player_pause.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/resources/icons/pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon9.addPixmap(QtGui.QPixmap(":/icons/resources/icons/pause_disabled.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        self.btn_transcribe_player_pause.setIcon(icon9)
        self.btn_transcribe_player_pause.setIconSize(QtCore.QSize(24, 24))
        self.btn_transcribe_player_pause.setObjectName("btn_transcribe_player_pause")
        self.gridLayout.addWidget(self.btn_transcribe_player_pause, 1, 1, 1, 1)
        self.btn_transcribe_player_play = QtWidgets.QPushButton(self.frm_transcribe_player_buttons)
        self.btn_transcribe_player_play.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_transcribe_player_play.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_transcribe_player_play.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/resources/icons/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon10.addPixmap(QtGui.QPixmap(":/icons/resources/icons/play_disabled.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        self.btn_transcribe_player_play.setIcon(icon10)
        self.btn_transcribe_player_play.setIconSize(QtCore.QSize(24, 24))
        self.btn_transcribe_player_play.setObjectName("btn_transcribe_player_play")
        self.gridLayout.addWidget(self.btn_transcribe_player_play, 1, 0, 1, 1)
        self.btn_transcribe_player_stop = QtWidgets.QPushButton(self.frm_transcribe_player_buttons)
        self.btn_transcribe_player_stop.setEnabled(True)
        self.btn_transcribe_player_stop.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_transcribe_player_stop.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_transcribe_player_stop.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icons/resources/icons/stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon11.addPixmap(QtGui.QPixmap(":/icons/resources/icons/stop_disabled.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        self.btn_transcribe_player_stop.setIcon(icon11)
        self.btn_transcribe_player_stop.setIconSize(QtCore.QSize(24, 24))
        self.btn_transcribe_player_stop.setObjectName("btn_transcribe_player_stop")
        self.gridLayout.addWidget(self.btn_transcribe_player_stop, 1, 2, 1, 1)
        self.btn_transcribe_player_playSelected = QtWidgets.QPushButton(self.frm_transcribe_player_buttons)
        self.btn_transcribe_player_playSelected.setEnabled(True)
        self.btn_transcribe_player_playSelected.setMinimumSize(QtCore.QSize(0, 25))
        self.btn_transcribe_player_playSelected.setMaximumSize(QtCore.QSize(90, 25))
        self.btn_transcribe_player_playSelected.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_transcribe_player_playSelected.setObjectName("btn_transcribe_player_playSelected")
        self.gridLayout.addWidget(self.btn_transcribe_player_playSelected, 0, 0, 1, 3)
        self.horizontalLayout_8.addWidget(self.frm_transcribe_player_buttons)
        self.frm_transcribe_player_slider = QtWidgets.QFrame(self.frm_transcribe_player)
        self.frm_transcribe_player_slider.setMaximumSize(QtCore.QSize(16777215, 65))
        self.frm_transcribe_player_slider.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_transcribe_player_slider.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_transcribe_player_slider.setObjectName("frm_transcribe_player_slider")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frm_transcribe_player_slider)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.sld_transcribe_player = QtWidgets.QSlider(self.frm_transcribe_player_slider)
        self.sld_transcribe_player.setMinimumSize(QtCore.QSize(0, 31))
        self.sld_transcribe_player.setMaximumSize(QtCore.QSize(16777215, 31))
        self.sld_transcribe_player.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.sld_transcribe_player.setMaximum(3599)
        self.sld_transcribe_player.setOrientation(QtCore.Qt.Horizontal)
        self.sld_transcribe_player.setObjectName("sld_transcribe_player")
        self.gridLayout_4.addWidget(self.sld_transcribe_player, 1, 2, 1, 1)
        self.lbl_transcribe_player_length = QtWidgets.QLabel(self.frm_transcribe_player_slider)
        self.lbl_transcribe_player_length.setMinimumSize(QtCore.QSize(40, 31))
        self.lbl_transcribe_player_length.setMaximumSize(QtCore.QSize(40, 31))
        self.lbl_transcribe_player_length.setObjectName("lbl_transcribe_player_length")
        self.gridLayout_4.addWidget(self.lbl_transcribe_player_length, 1, 3, 1, 1)
        self.lbl_transcribe_player_timer = QtWidgets.QLabel(self.frm_transcribe_player_slider)
        self.lbl_transcribe_player_timer.setMinimumSize(QtCore.QSize(40, 31))
        self.lbl_transcribe_player_timer.setMaximumSize(QtCore.QSize(40, 31))
        self.lbl_transcribe_player_timer.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_transcribe_player_timer.setObjectName("lbl_transcribe_player_timer")
        self.gridLayout_4.addWidget(self.lbl_transcribe_player_timer, 1, 1, 1, 1)
        self.lbl_transcribe_player_status = QtWidgets.QLabel(self.frm_transcribe_player_slider)
        font = QtGui.QFont()
        font.setFamily("Palatino")
        font.setPointSize(6)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lbl_transcribe_player_status.setFont(font)
        self.lbl_transcribe_player_status.setText("")
        self.lbl_transcribe_player_status.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_transcribe_player_status.setObjectName("lbl_transcribe_player_status")
        self.gridLayout_4.addWidget(self.lbl_transcribe_player_status, 0, 2, 1, 1)
        self.horizontalLayout_8.addWidget(self.frm_transcribe_player_slider, 0, QtCore.Qt.AlignBottom)
        self.verticalLayout_9.addWidget(self.frm_transcribe_player)
        self.verticalLayout_8.addWidget(self.frm_transcribe_top)
        self.frm_transcribe_separator = QtWidgets.QFrame(self.frm_transcribe)
        self.frm_transcribe_separator.setMinimumSize(QtCore.QSize(0, 5))
        self.frm_transcribe_separator.setMaximumSize(QtCore.QSize(16777215, 5))
        self.frm_transcribe_separator.setStyleSheet("")
        self.frm_transcribe_separator.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_transcribe_separator.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_transcribe_separator.setObjectName("frm_transcribe_separator")
        self.verticalLayout_8.addWidget(self.frm_transcribe_separator)
        self.frm_transcribe_bottom = QtWidgets.QFrame(self.frm_transcribe)
        self.frm_transcribe_bottom.setMinimumSize(QtCore.QSize(0, 280))
        self.frm_transcribe_bottom.setMaximumSize(QtCore.QSize(16777215, 280))
        self.frm_transcribe_bottom.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_transcribe_bottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_transcribe_bottom.setObjectName("frm_transcribe_bottom")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frm_transcribe_bottom)
        self.verticalLayout_13.setContentsMargins(9, 9, 9, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.frm_transcribe_input = QtWidgets.QFrame(self.frm_transcribe_bottom)
        self.frm_transcribe_input.setMaximumSize(QtCore.QSize(16777215, 85))
        self.frm_transcribe_input.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_transcribe_input.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_transcribe_input.setObjectName("frm_transcribe_input")
        self.formLayout_2 = QtWidgets.QFormLayout(self.frm_transcribe_input)
        self.formLayout_2.setContentsMargins(0, 5, 0, 0)
        self.formLayout_2.setHorizontalSpacing(0)
        self.formLayout_2.setVerticalSpacing(30)
        self.formLayout_2.setObjectName("formLayout_2")
        self.lbl_transcribe_language = QtWidgets.QLabel(self.frm_transcribe_input)
        self.lbl_transcribe_language.setMinimumSize(QtCore.QSize(120, 25))
        self.lbl_transcribe_language.setMaximumSize(QtCore.QSize(120, 25))
        self.lbl_transcribe_language.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_transcribe_language.setObjectName("lbl_transcribe_language")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbl_transcribe_language)
        self.cbo_transcribe_language = QtWidgets.QComboBox(self.frm_transcribe_input)
        self.cbo_transcribe_language.setMinimumSize(QtCore.QSize(0, 25))
        self.cbo_transcribe_language.setMaximumSize(QtCore.QSize(150, 25))
        self.cbo_transcribe_language.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cbo_transcribe_language.setObjectName("cbo_transcribe_language")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cbo_transcribe_language)
        self.lbl_transcribe_output = QtWidgets.QLabel(self.frm_transcribe_input)
        self.lbl_transcribe_output.setMinimumSize(QtCore.QSize(120, 27))
        self.lbl_transcribe_output.setMaximumSize(QtCore.QSize(120, 27))
        self.lbl_transcribe_output.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_transcribe_output.setObjectName("lbl_transcribe_output")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lbl_transcribe_output)
        self.frm_transcribe_output = QtWidgets.QFrame(self.frm_transcribe_input)
        self.frm_transcribe_output.setMinimumSize(QtCore.QSize(0, 26))
        self.frm_transcribe_output.setMaximumSize(QtCore.QSize(16777215, 26))
        self.frm_transcribe_output.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_transcribe_output.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_transcribe_output.setObjectName("frm_transcribe_output")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frm_transcribe_output)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.txt_transcribe_output = QtWidgets.QLineEdit(self.frm_transcribe_output)
        self.txt_transcribe_output.setMinimumSize(QtCore.QSize(0, 25))
        self.txt_transcribe_output.setMaximumSize(QtCore.QSize(16777215, 25))
        self.txt_transcribe_output.setObjectName("txt_transcribe_output")
        self.horizontalLayout_12.addWidget(self.txt_transcribe_output)
        self.btn_transcribe_output = QtWidgets.QPushButton(self.frm_transcribe_output)
        self.btn_transcribe_output.setMinimumSize(QtCore.QSize(60, 25))
        self.btn_transcribe_output.setMaximumSize(QtCore.QSize(60, 25))
        self.btn_transcribe_output.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_transcribe_output.setObjectName("btn_transcribe_output")
        self.horizontalLayout_12.addWidget(self.btn_transcribe_output)
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.frm_transcribe_output)
        self.verticalLayout_13.addWidget(self.frm_transcribe_input)
        self.frm_transcribe_transcribe = QtWidgets.QFrame(self.frm_transcribe_bottom)
        self.frm_transcribe_transcribe.setMinimumSize(QtCore.QSize(0, 160))
        self.frm_transcribe_transcribe.setMaximumSize(QtCore.QSize(16777215, 160))
        self.frm_transcribe_transcribe.setStyleSheet("")
        self.frm_transcribe_transcribe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_transcribe_transcribe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_transcribe_transcribe.setObjectName("frm_transcribe_transcribe")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frm_transcribe_transcribe)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.btn_transcribe_transcribe = QtWidgets.QPushButton(self.frm_transcribe_transcribe)
        self.btn_transcribe_transcribe.setMinimumSize(QtCore.QSize(0, 45))
        self.btn_transcribe_transcribe.setMaximumSize(QtCore.QSize(16777215, 45))
        self.btn_transcribe_transcribe.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_transcribe_transcribe.setObjectName("btn_transcribe_transcribe")
        self.verticalLayout_15.addWidget(self.btn_transcribe_transcribe)
        self.pgr_transcribe_transcribe = QtWidgets.QProgressBar(self.frm_transcribe_transcribe)
        self.pgr_transcribe_transcribe.setMinimumSize(QtCore.QSize(0, 21))
        self.pgr_transcribe_transcribe.setMaximumSize(QtCore.QSize(16777215, 21))
        self.pgr_transcribe_transcribe.setProperty("value", 0)
        self.pgr_transcribe_transcribe.setObjectName("pgr_transcribe_transcribe")
        self.verticalLayout_15.addWidget(self.pgr_transcribe_transcribe)
        self.lbl_transcribe_status = QtWidgets.QLabel(self.frm_transcribe_transcribe)
        self.lbl_transcribe_status.setMinimumSize(QtCore.QSize(0, 21))
        self.lbl_transcribe_status.setMaximumSize(QtCore.QSize(16777215, 21))
        self.lbl_transcribe_status.setText("")
        self.lbl_transcribe_status.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_transcribe_status.setObjectName("lbl_transcribe_status")
        self.verticalLayout_15.addWidget(self.lbl_transcribe_status)
        self.btn_transcribe_cancel = QtWidgets.QPushButton(self.frm_transcribe_transcribe)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_transcribe_cancel.sizePolicy().hasHeightForWidth())
        self.btn_transcribe_cancel.setSizePolicy(sizePolicy)
        self.btn_transcribe_cancel.setMinimumSize(QtCore.QSize(100, 30))
        self.btn_transcribe_cancel.setMaximumSize(QtCore.QSize(150, 30))
        self.btn_transcribe_cancel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_transcribe_cancel.setObjectName("btn_transcribe_cancel")
        self.verticalLayout_15.addWidget(self.btn_transcribe_cancel, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_13.addWidget(self.frm_transcribe_transcribe)
        self.verticalLayout_8.addWidget(self.frm_transcribe_bottom)
        self.verticalLayout_6.addWidget(self.frm_transcribe)
        self.stackedWidget.addWidget(self.pg_transcribe)
        self.pg_translate = QtWidgets.QWidget()
        self.pg_translate.setStyleSheet("/* Translate */\n"
"#frm_translate_top > QFrame{\n"
"    border: 1px solid transparent;\n"
"    border-radius: 15px;\n"
"    background-color: #272c36;\n"
"}\n"
"#frm_translate_bottom{\n"
"    border: 1px solid transparent;\n"
"    border-radius: 15px;\n"
"    background-color: #272c36;\n"
"    margin: 9px;\n"
"}\n"
"#frm_translate_separator{\n"
"    border-radius: 0px;\n"
"    background-color: #3d4656;\n"
"}\n"
"\n"
"/* Translate File Frame */\n"
"#lbl_translate_title{\n"
"    font:bold 14pt \'Segoe UI\';\n"
"    color: #cccccc;\n"
"    padding-left: 1px;\n"
"}\n"
"#frm_translate_file_buttons{\n"
"    height: 30px;\n"
"}\n"
"\n"
"/* Translate Input */\n"
"#frm_translate_input QLabel{\n"
"    font: 10pt \'Franklin Gothic Medium\';\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;\n"
"}\n"
"#btn_translate_output{\n"
"    border: 1px solid #7a7a7a;\n"
"    border-radius: 0px;\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"#grp_translate_googleTranslate{\n"
"    font: bold 10pt \'Franklin Gothic Medium\';\n"
"    text-decoration: underline;\n"
"}\n"
"\n"
"/* Translate Form Translate */\n"
"#pgr_translate_translate{\n"
"    margin-bottom: -20px;\n"
"}\n"
"#lbl_translate_status{\n"
"    font: italic Arial, Helvetica, sans-serif;\n"
"    margin-top: -20px;\n"
"}\n"
"#frm_translate_translate > QPushButton{\n"
"    border: 4px ridge #333d50;\n"
"    border-radius: 15px;\n"
"}\n"
"#frm_translate_translate > QPushButton:hover{\n"
"    border: 4px ridge #3e4c66;\n"
"}\n"
"#frm_translate_translate > QPushButton:pressed{\n"
"    border: 4px solid #15171a;\n"
"}\n"
"#btn_translate_translate{\n"
"    font: bold 12pt \"Secular One\";\n"
"}\n"
"#btn_translate_cancel{\n"
"    font: \'Segoe UI\';\n"
"}")
        self.pg_translate.setObjectName("pg_translate")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.pg_translate)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frm_translate = QtWidgets.QFrame(self.pg_translate)
        self.frm_translate.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_translate.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_translate.setObjectName("frm_translate")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.frm_translate)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.frm_translate_top = QtWidgets.QFrame(self.frm_translate)
        self.frm_translate_top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_translate_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_translate_top.setObjectName("frm_translate_top")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frm_translate_top)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.frm_translate_file = QtWidgets.QFrame(self.frm_translate_top)
        self.frm_translate_file.setEnabled(True)
        self.frm_translate_file.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_translate_file.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_translate_file.setObjectName("frm_translate_file")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frm_translate_file)
        self.verticalLayout_16.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_16.setSpacing(8)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.lbl_translate_title = QtWidgets.QLabel(self.frm_translate_file)
        self.lbl_translate_title.setMinimumSize(QtCore.QSize(0, 24))
        self.lbl_translate_title.setMaximumSize(QtCore.QSize(16777215, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.lbl_translate_title.setFont(font)
        self.lbl_translate_title.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_translate_title.setObjectName("lbl_translate_title")
        self.verticalLayout_16.addWidget(self.lbl_translate_title)
        self.frm_translate_file_buttons = QtWidgets.QFrame(self.frm_translate_file)
        self.frm_translate_file_buttons.setMaximumSize(QtCore.QSize(68, 65))
        self.frm_translate_file_buttons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_translate_file_buttons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_translate_file_buttons.setObjectName("frm_translate_file_buttons")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frm_translate_file_buttons)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(5)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.btn_translate_file_add = QtWidgets.QPushButton(self.frm_translate_file_buttons)
        self.btn_translate_file_add.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_translate_file_add.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_translate_file_add.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_translate_file_add.setText("")
        self.btn_translate_file_add.setIcon(icon6)
        self.btn_translate_file_add.setObjectName("btn_translate_file_add")
        self.horizontalLayout_10.addWidget(self.btn_translate_file_add)
        self.btn_translate_file_remove = QtWidgets.QPushButton(self.frm_translate_file_buttons)
        self.btn_translate_file_remove.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_translate_file_remove.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_translate_file_remove.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_translate_file_remove.setText("")
        self.btn_translate_file_remove.setIcon(icon7)
        self.btn_translate_file_remove.setObjectName("btn_translate_file_remove")
        self.horizontalLayout_10.addWidget(self.btn_translate_file_remove)
        self.verticalLayout_16.addWidget(self.frm_translate_file_buttons)
        self.frm_translate_file_list = QtWidgets.QFrame(self.frm_translate_file)
        self.frm_translate_file_list.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_translate_file_list.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_translate_file_list.setObjectName("frm_translate_file_list")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.frm_translate_file_list)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setSpacing(0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.lst_translate_file = QtWidgets.QListWidget(self.frm_translate_file_list)
        self.lst_translate_file.setAlternatingRowColors(False)
        self.lst_translate_file.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.lst_translate_file.setObjectName("lst_translate_file")
        self.verticalLayout_17.addWidget(self.lst_translate_file)
        self.verticalLayout_16.addWidget(self.frm_translate_file_list)
        self.verticalLayout_14.addWidget(self.frm_translate_file)
        self.verticalLayout_21.addWidget(self.frm_translate_top)
        self.frm_translate_separator = QtWidgets.QFrame(self.frm_translate)
        self.frm_translate_separator.setMinimumSize(QtCore.QSize(0, 5))
        self.frm_translate_separator.setMaximumSize(QtCore.QSize(16777215, 5))
        self.frm_translate_separator.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_translate_separator.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_translate_separator.setObjectName("frm_translate_separator")
        self.verticalLayout_21.addWidget(self.frm_translate_separator)
        self.frm_translate_bottom = QtWidgets.QFrame(self.frm_translate)
        self.frm_translate_bottom.setMinimumSize(QtCore.QSize(0, 351))
        self.frm_translate_bottom.setMaximumSize(QtCore.QSize(16777215, 351))
        self.frm_translate_bottom.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_translate_bottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_translate_bottom.setObjectName("frm_translate_bottom")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.frm_translate_bottom)
        self.verticalLayout_19.setContentsMargins(9, 0, 9, 0)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.frm_translate_input = QtWidgets.QFrame(self.frm_translate_bottom)
        self.frm_translate_input.setMinimumSize(QtCore.QSize(0, 180))
        self.frm_translate_input.setMaximumSize(QtCore.QSize(16777215, 180))
        self.frm_translate_input.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_translate_input.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_translate_input.setObjectName("frm_translate_input")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.frm_translate_input)
        self.verticalLayout_22.setContentsMargins(0, 0, 0, 15)
        self.verticalLayout_22.setSpacing(0)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.frm_translate_selections = QtWidgets.QFrame(self.frm_translate_input)
        self.frm_translate_selections.setMinimumSize(QtCore.QSize(0, 101))
        self.frm_translate_selections.setMaximumSize(QtCore.QSize(16777215, 101))
        self.frm_translate_selections.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_translate_selections.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_translate_selections.setObjectName("frm_translate_selections")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frm_translate_selections)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setSpacing(50)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.frm_translate_model = QtWidgets.QFrame(self.frm_translate_selections)
        self.frm_translate_model.setMinimumSize(QtCore.QSize(0, 90))
        self.frm_translate_model.setMaximumSize(QtCore.QSize(270, 90))
        self.frm_translate_model.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_translate_model.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_translate_model.setObjectName("frm_translate_model")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frm_translate_model)
        self.horizontalLayout_14.setContentsMargins(0, 64, 0, 0)
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.lbl_translate_model = QtWidgets.QLabel(self.frm_translate_model)
        self.lbl_translate_model.setMinimumSize(QtCore.QSize(119, 25))
        self.lbl_translate_model.setMaximumSize(QtCore.QSize(119, 25))
        self.lbl_translate_model.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_translate_model.setObjectName("lbl_translate_model")
        self.horizontalLayout_14.addWidget(self.lbl_translate_model)
        self.cbo_translate_model = QtWidgets.QComboBox(self.frm_translate_model)
        self.cbo_translate_model.setMinimumSize(QtCore.QSize(150, 25))
        self.cbo_translate_model.setMaximumSize(QtCore.QSize(150, 25))
        self.cbo_translate_model.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cbo_translate_model.setObjectName("cbo_translate_model")
        self.horizontalLayout_14.addWidget(self.cbo_translate_model)
        self.horizontalLayout_13.addWidget(self.frm_translate_model)
        self.frm_translate_googleTranslate = QtWidgets.QFrame(self.frm_translate_selections)
        self.frm_translate_googleTranslate.setMinimumSize(QtCore.QSize(0, 90))
        self.frm_translate_googleTranslate.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frm_translate_googleTranslate.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_translate_googleTranslate.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_translate_googleTranslate.setObjectName("frm_translate_googleTranslate")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.frm_translate_googleTranslate)
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_18.setSpacing(0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.grp_translate_googleTranslate = QtWidgets.QGroupBox(self.frm_translate_googleTranslate)
        self.grp_translate_googleTranslate.setMinimumSize(QtCore.QSize(525, 90))
        self.grp_translate_googleTranslate.setMaximumSize(QtCore.QSize(550, 90))
        self.grp_translate_googleTranslate.setObjectName("grp_translate_googleTranslate")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.grp_translate_googleTranslate)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.chk_translate_googleTranslate = QtWidgets.QCheckBox(self.grp_translate_googleTranslate)
        self.chk_translate_googleTranslate.setEnabled(True)
        self.chk_translate_googleTranslate.setObjectName("chk_translate_googleTranslate")
        self.gridLayout_2.addWidget(self.chk_translate_googleTranslate, 0, 0, 1, 2)
        self.lbl_translate_sourceLanguage = QtWidgets.QLabel(self.grp_translate_googleTranslate)
        self.lbl_translate_sourceLanguage.setMinimumSize(QtCore.QSize(125, 0))
        self.lbl_translate_sourceLanguage.setMaximumSize(QtCore.QSize(125, 16777215))
        self.lbl_translate_sourceLanguage.setObjectName("lbl_translate_sourceLanguage")
        self.gridLayout_2.addWidget(self.lbl_translate_sourceLanguage, 1, 0, 1, 1)
        self.cbo_translate_sourceLanguage = QtWidgets.QComboBox(self.grp_translate_googleTranslate)
        self.cbo_translate_sourceLanguage.setMinimumSize(QtCore.QSize(135, 0))
        self.cbo_translate_sourceLanguage.setMaximumSize(QtCore.QSize(135, 16777215))
        self.cbo_translate_sourceLanguage.setObjectName("cbo_translate_sourceLanguage")
        self.gridLayout_2.addWidget(self.cbo_translate_sourceLanguage, 1, 1, 1, 1)
        self.lbl_translate_outputLanguage = QtWidgets.QLabel(self.grp_translate_googleTranslate)
        self.lbl_translate_outputLanguage.setMinimumSize(QtCore.QSize(95, 0))
        self.lbl_translate_outputLanguage.setMaximumSize(QtCore.QSize(95, 16777215))
        self.lbl_translate_outputLanguage.setObjectName("lbl_translate_outputLanguage")
        self.gridLayout_2.addWidget(self.lbl_translate_outputLanguage, 1, 2, 1, 1)
        self.cbo_translate_outputLanguage = QtWidgets.QComboBox(self.grp_translate_googleTranslate)
        self.cbo_translate_outputLanguage.setEnabled(True)
        self.cbo_translate_outputLanguage.setMinimumSize(QtCore.QSize(135, 0))
        self.cbo_translate_outputLanguage.setMaximumSize(QtCore.QSize(135, 16777215))
        self.cbo_translate_outputLanguage.setObjectName("cbo_translate_outputLanguage")
        self.gridLayout_2.addWidget(self.cbo_translate_outputLanguage, 1, 3, 1, 1)
        self.verticalLayout_18.addWidget(self.grp_translate_googleTranslate)
        self.horizontalLayout_13.addWidget(self.frm_translate_googleTranslate)
        self.verticalLayout_22.addWidget(self.frm_translate_selections)
        self.frm_translate_output = QtWidgets.QFrame(self.frm_translate_input)
        self.frm_translate_output.setMinimumSize(QtCore.QSize(0, 27))
        self.frm_translate_output.setMaximumSize(QtCore.QSize(16777215, 27))
        self.frm_translate_output.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_translate_output.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_translate_output.setObjectName("frm_translate_output")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frm_translate_output)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.lbl_translate_output = QtWidgets.QLabel(self.frm_translate_output)
        self.lbl_translate_output.setMinimumSize(QtCore.QSize(120, 25))
        self.lbl_translate_output.setMaximumSize(QtCore.QSize(120, 25))
        self.lbl_translate_output.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_translate_output.setObjectName("lbl_translate_output")
        self.horizontalLayout_11.addWidget(self.lbl_translate_output)
        self.txt_translate_output = QtWidgets.QLineEdit(self.frm_translate_output)
        self.txt_translate_output.setMinimumSize(QtCore.QSize(0, 25))
        self.txt_translate_output.setMaximumSize(QtCore.QSize(16777215, 25))
        self.txt_translate_output.setObjectName("txt_translate_output")
        self.horizontalLayout_11.addWidget(self.txt_translate_output)
        self.btn_translate_output = QtWidgets.QPushButton(self.frm_translate_output)
        self.btn_translate_output.setMinimumSize(QtCore.QSize(60, 25))
        self.btn_translate_output.setMaximumSize(QtCore.QSize(60, 25))
        self.btn_translate_output.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_translate_output.setToolTip("")
        self.btn_translate_output.setObjectName("btn_translate_output")
        self.horizontalLayout_11.addWidget(self.btn_translate_output)
        self.verticalLayout_22.addWidget(self.frm_translate_output)
        self.verticalLayout_19.addWidget(self.frm_translate_input)
        self.frm_translate_translate = QtWidgets.QFrame(self.frm_translate_bottom)
        self.frm_translate_translate.setEnabled(True)
        self.frm_translate_translate.setMinimumSize(QtCore.QSize(0, 160))
        self.frm_translate_translate.setMaximumSize(QtCore.QSize(16777215, 160))
        self.frm_translate_translate.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_translate_translate.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_translate_translate.setObjectName("frm_translate_translate")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.frm_translate_translate)
        self.verticalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_20.setSpacing(0)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.btn_translate_translate = QtWidgets.QPushButton(self.frm_translate_translate)
        self.btn_translate_translate.setMinimumSize(QtCore.QSize(0, 45))
        self.btn_translate_translate.setMaximumSize(QtCore.QSize(16777215, 45))
        self.btn_translate_translate.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_translate_translate.setToolTip("")
        self.btn_translate_translate.setObjectName("btn_translate_translate")
        self.verticalLayout_20.addWidget(self.btn_translate_translate)
        self.pgr_translate_translate = QtWidgets.QProgressBar(self.frm_translate_translate)
        self.pgr_translate_translate.setMinimumSize(QtCore.QSize(0, 21))
        self.pgr_translate_translate.setMaximumSize(QtCore.QSize(16777215, 21))
        self.pgr_translate_translate.setProperty("value", 0)
        self.pgr_translate_translate.setObjectName("pgr_translate_translate")
        self.verticalLayout_20.addWidget(self.pgr_translate_translate)
        self.lbl_translate_status = QtWidgets.QLabel(self.frm_translate_translate)
        self.lbl_translate_status.setMinimumSize(QtCore.QSize(0, 21))
        self.lbl_translate_status.setMaximumSize(QtCore.QSize(16777215, 21))
        self.lbl_translate_status.setText("")
        self.lbl_translate_status.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_translate_status.setObjectName("lbl_translate_status")
        self.verticalLayout_20.addWidget(self.lbl_translate_status)
        self.btn_translate_cancel = QtWidgets.QPushButton(self.frm_translate_translate)
        self.btn_translate_cancel.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_translate_cancel.sizePolicy().hasHeightForWidth())
        self.btn_translate_cancel.setSizePolicy(sizePolicy)
        self.btn_translate_cancel.setMinimumSize(QtCore.QSize(100, 30))
        self.btn_translate_cancel.setMaximumSize(QtCore.QSize(150, 30))
        self.btn_translate_cancel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_translate_cancel.setObjectName("btn_translate_cancel")
        self.verticalLayout_20.addWidget(self.btn_translate_cancel, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_19.addWidget(self.frm_translate_translate)
        self.verticalLayout_21.addWidget(self.frm_translate_bottom)
        self.verticalLayout_7.addWidget(self.frm_translate)
        self.stackedWidget.addWidget(self.pg_translate)
        self.verticalLayout_5.addWidget(self.stackedWidget)
        self.horizontalLayout.addWidget(self.frm_content)
        self.verticalLayout_27.addWidget(self.frm_display)
        self.gridLayout_3.addWidget(self.frm_main, 2, 1, 1, 1)
        self.window_top = QtWidgets.QFrame(self.frm_window)
        self.window_top.setMinimumSize(QtCore.QSize(0, 0))
        self.window_top.setMaximumSize(QtCore.QSize(16777215, 2))
        self.window_top.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.window_top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.window_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.window_top.setObjectName("window_top")
        self.gridLayout_3.addWidget(self.window_top, 0, 1, 1, 1)
        self.window_bottomRight = QtWidgets.QFrame(self.frm_window)
        self.window_bottomRight.setMinimumSize(QtCore.QSize(0, 0))
        self.window_bottomRight.setMaximumSize(QtCore.QSize(2, 2))
        self.window_bottomRight.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.window_bottomRight.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.window_bottomRight.setFrameShadow(QtWidgets.QFrame.Raised)
        self.window_bottomRight.setObjectName("window_bottomRight")
        self.gridLayout_3.addWidget(self.window_bottomRight, 3, 2, 1, 1)
        self.window_bottom = QtWidgets.QFrame(self.frm_window)
        self.window_bottom.setMinimumSize(QtCore.QSize(0, 0))
        self.window_bottom.setMaximumSize(QtCore.QSize(16777215, 2))
        self.window_bottom.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.window_bottom.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.window_bottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.window_bottom.setObjectName("window_bottom")
        self.gridLayout_3.addWidget(self.window_bottom, 3, 1, 1, 1)
        self.window_bottomLeft = QtWidgets.QFrame(self.frm_window)
        self.window_bottomLeft.setMinimumSize(QtCore.QSize(0, 0))
        self.window_bottomLeft.setMaximumSize(QtCore.QSize(2, 2))
        self.window_bottomLeft.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.window_bottomLeft.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.window_bottomLeft.setFrameShadow(QtWidgets.QFrame.Raised)
        self.window_bottomLeft.setObjectName("window_bottomLeft")
        self.gridLayout_3.addWidget(self.window_bottomLeft, 3, 0, 1, 1)
        self.verticalLayout.addWidget(self.frm_window)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Captionizer"))
        self.lbl_windowLogo.setToolTip(_translate("MainWindow", "Captionizer"))
        self.lbl_windowTitle.setToolTip(_translate("MainWindow", "Captionizer"))
        self.lbl_windowTitle.setText(_translate("MainWindow", "Captionizer"))
        self.mnu_file.setText(_translate("MainWindow", "&File"))
        self.mnu_history.setText(_translate("MainWindow", "&History"))
        self.btn_minimize.setToolTip(_translate("MainWindow", "Minimize"))
        self.btn_maximize.setToolTip(_translate("MainWindow", "Maximize"))
        self.btn_close.setToolTip(_translate("MainWindow", "Close"))
        self.btn_menu.setText(_translate("MainWindow", "MENU"))
        self.btn_menuTranscription.setText(_translate("MainWindow", "FILE TRANSCRIPTION"))
        self.btn_menuTranslation.setText(_translate("MainWindow", "FILE TRANSLATION"))
        self.lbl_mainMenu_title.setText(_translate("MainWindow", "Captionizer"))
        self.btn_mainMenu_transcription.setText(_translate("MainWindow", "    FILE TRANSCRIPTION"))
        self.btn_mainMenu_translation.setText(_translate("MainWindow", "    FILE TRANSLATION"))
        self.lbl_transcribe_title.setText(_translate("MainWindow", "FILE TRANSCRIPTION"))
        self.btn_transcribe_file_add.setToolTip(_translate("MainWindow", "Add File"))
        self.btn_transcribe_file_remove.setToolTip(_translate("MainWindow", "Remove File"))
        self.btn_transcribe_file_record.setToolTip(_translate("MainWindow", "Record Audio"))
        self.lst_transcribe_file.setToolTip(_translate("MainWindow", "Drop a file to import"))
        self.btn_transcribe_player_pause.setToolTip(_translate("MainWindow", "Pause"))
        self.btn_transcribe_player_play.setToolTip(_translate("MainWindow", "Play"))
        self.btn_transcribe_player_stop.setToolTip(_translate("MainWindow", "Stop"))
        self.btn_transcribe_player_playSelected.setToolTip(_translate("MainWindow", "Play Selected File"))
        self.btn_transcribe_player_playSelected.setText(_translate("MainWindow", "Play Selected"))
        self.lbl_transcribe_player_length.setText(_translate("MainWindow", "59:59"))
        self.lbl_transcribe_player_timer.setText(_translate("MainWindow", "00:00"))
        self.lbl_transcribe_language.setText(_translate("MainWindow", "Audio Language:"))
        self.lbl_transcribe_output.setText(_translate("MainWindow", "Output Path:"))
        self.txt_transcribe_output.setPlaceholderText(_translate("MainWindow", "[LEAVE EMPTY TO OUTPUT BESIDE MEDIA FILE]"))
        self.btn_transcribe_output.setText(_translate("MainWindow", "Browse"))
        self.btn_transcribe_transcribe.setText(_translate("MainWindow", "Transcribe"))
        self.btn_transcribe_cancel.setText(_translate("MainWindow", "Cancel"))
        self.lbl_translate_title.setText(_translate("MainWindow", "FILE TRANSLATION"))
        self.btn_translate_file_add.setToolTip(_translate("MainWindow", "Add File"))
        self.btn_translate_file_remove.setToolTip(_translate("MainWindow", "Remove File"))
        self.lst_translate_file.setToolTip(_translate("MainWindow", "Drop a file to add"))
        self.lbl_translate_model.setText(_translate("MainWindow", "Model:"))
        self.grp_translate_googleTranslate.setTitle(_translate("MainWindow", "  Google Translate  "))
        self.chk_translate_googleTranslate.setText(_translate("MainWindow", "Use Google Translate"))
        self.lbl_translate_sourceLanguage.setText(_translate("MainWindow", "Caption Language:"))
        self.lbl_translate_outputLanguage.setText(_translate("MainWindow", "Translate To:"))
        self.lbl_translate_output.setText(_translate("MainWindow", "Output Path:"))
        self.txt_translate_output.setPlaceholderText(_translate("MainWindow", "[LEAVE EMPTY TO OUTPUT BESIDE MEDIA FILE]"))
        self.btn_translate_output.setText(_translate("MainWindow", "Browse"))
        self.btn_translate_translate.setText(_translate("MainWindow", "Translate"))
        self.btn_translate_cancel.setText(_translate("MainWindow", "Cancel"))
import resources_rc
